#!/usr/bin/env python3
"""Keep the plugin's model YAMLs in sync with the live ZenMux catalog.

Subcommands:
  fetch   Pull the official catalog (+ undocumented website metadata as enrichment)
          and write a normalized snapshot to catalog/snapshot.json.
  probe   Run cheap live requests that the catalog cannot answer (tool calling,
          reasoning_effort values, Claude temperature/adaptive thinking, embedding
          batching, whether embedding/rerank models really use images) and record
          results in catalog/probes.json. Needs ZENMUX_PROBE_API_KEY.
  sync    Generate models/**/*.yaml and _position.yaml from snapshot + probes +
          catalog/overrides.yaml, and print a change report (usable as PR body).
  check   Exit non-zero if the committed YAMLs differ from what `sync` would generate.

Sources of truth, in priority order: overrides.yaml > probes.json > official catalog
> website metadata > template defaults.
"""

import argparse
import base64
import concurrent.futures
import datetime
import json
import math
import os
import re
import struct
import sys
import urllib.error
import urllib.request
import zlib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATALOG_DIR = ROOT / "catalog"
SNAPSHOT = CATALOG_DIR / "snapshot.json"
PROBES = CATALOG_DIR / "probes.json"
OVERRIDES = CATALOG_DIR / "overrides.yaml"
MODEL_DIRS = {
    "llm": ROOT / "models" / "llm",
    "text-embedding": ROOT / "models" / "text_embedding",
    "rerank": ROOT / "models" / "rerank",
}

API_BASE = "https://zenmux.ai"
OFFICIAL_URL = f"{API_BASE}/api/v1/models"
FRONTEND_URL = f"{API_BASE}/api/frontend/model/listByFilter"
TYPE_BY_OUTPUT = {("text",): "llm", ("embeddings",): "text-embedding", ("rerank",): "rerank"}
GENERATED_HEADER = "# Generated by scripts/zenmux_models.py - edit catalog/overrides.yaml instead.\n"
ALL_EFFORTS = ["none", "minimal", "low", "medium", "high", "xhigh", "max"]
DEFAULT_MAX_TOKENS = 8192


# ── IO helpers ───────────────────────────────────────────────────────────────

def http_json(url, body=None, headers=None, timeout=60):
    data = json.dumps(body).encode() if body is not None else None
    # The website endpoint rejects the default urllib User-Agent.
    base_headers = {"Content-Type": "application/json", "User-Agent": "zenmux-dify-plugin-sync/1.0 (+curl compatible)"}
    req = urllib.request.Request(url, data=data, headers={**base_headers, **(headers or {})})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.load(resp)


def load_json(path, default):
    return json.loads(path.read_text()) if path.exists() else default


def dump_yaml(data) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=1000)


def today():
    return datetime.date.today().isoformat()


# ── fetch ────────────────────────────────────────────────────────────────────

def first_tier(pricings, key):
    """Base-tier price: the tier whose conditions start lowest (or has none)."""
    def start(tier):
        conds = tier.get("conditions") or {}
        return min((float(c.get("gte") or 0) for c in conds.values() if isinstance(c, dict)), default=0.0)

    tiers = (pricings or {}).get(key) or []
    return min(tiers, key=start)["value"] if tiers else None


def cmd_fetch(_args):
    official = http_json(OFFICIAL_URL)["data"]
    if len(official) < 50:
        sys.exit(f"official catalog returned only {len(official)} models; refusing to overwrite snapshot")
    try:
        frontend = {x["slug"]: x for x in http_json(FRONTEND_URL)["data"]}
    except Exception as exc:  # enrichment only; the sync falls back to overrides/defaults
        print(f"warning: website metadata unavailable ({exc}); max_output/params will fall back", file=sys.stderr)
        frontend = {}

    models = []
    for m in official:
        mtype = TYPE_BY_OUTPUT.get(tuple(m.get("output_modalities") or []))
        if not mtype:
            continue
        f = frontend.get(m["id"], {})
        pricings = m.get("pricings") or {}
        models.append({
            "id": m["id"],
            "name": m.get("display_name") or m["id"],
            "type": mtype,
            "publish_time": m.get("publish_time"),
            "input": m.get("input_modalities") or [],
            "context": m.get("context_length"),
            "reasoning": (m.get("capabilities") or {}).get("reasoning"),
            "price": {
                "input": first_tier(pricings, "prompt"),
                "output": first_tier(pricings, "completion"),
                "cache_read": first_tier(pricings, "input_cache_read"),
            } if first_tier(pricings, "prompt") is not None else None,
            "tiered": any(len(v) > 1 for v in pricings.values()),
            "max_output": f.get("max_completion_tokens"),
            "params": sorted(p for p in (f.get("supported_parameters") or "").split(",") if p),
            "website_reasoning": f.get("supports_reasoning"),
        })
    models.sort(key=lambda x: x["id"])
    CATALOG_DIR.mkdir(exist_ok=True)
    SNAPSHOT.write_text(json.dumps({"fetched_at": today(), "source": OFFICIAL_URL, "models": models}, indent=1, ensure_ascii=False) + "\n")
    counts = {t: sum(1 for m in models if m["type"] == t) for t in MODEL_DIRS}
    print(f"snapshot: {len(models)} in-scope models {counts} (official catalog total {len(official)})")


# ── shared model resolution ──────────────────────────────────────────────────

def load_inputs():
    if not SNAPSHOT.exists():
        sys.exit("catalog/snapshot.json missing; run `fetch` first")
    snapshot = load_json(SNAPSHOT, {})
    overrides = yaml.safe_load(OVERRIDES.read_text()) or {}
    probes = load_json(PROBES, {}).get("models", {})
    return snapshot, overrides, probes


def protocol_of(model_id: str) -> str:
    # Must stay in sync with models/llm/zenmux.py::protocol_of
    if model_id.startswith("anthropic/"):
        return "anthropic"
    if model_id.startswith("google/gemini-"):
        return "google"
    return "openai"


def resolve(m, overrides, probes):
    """Merge catalog entry with manual data. Returns (model, exclusion_reason)."""
    excl = overrides.get("exclude") or {}
    m = {**m, **((overrides.get("manual") or {}).get(m["id"]) or {}), **((overrides.get("models") or {}).get(m["id"]) or {})}
    if m["id"] in (excl.get("ids") or {}):
        return m, excl["ids"][m["id"]]
    probe = probes.get(m["id"]) or {}
    if probe.get("alive") is False:
        return m, f"retired upstream (probe {probe.get('checked_at')}): {probe.get('error')}"
    if any(m["id"].endswith(s) for s in excl.get("id_suffixes") or []):
        return m, "free model"
    price = m.get("price")
    if m["type"] != "rerank":
        if not price or price.get("input") is None:
            return m, "no pricing in catalog (verify via /management/generation, then add under `manual`)"
        if excl.get("zero_priced") and not price.get("input") and not price.get("output"):
            return m, "zero-priced (free)"
    if m.get("reasoning") is None:
        m["reasoning"] = bool(m.get("website_reasoning"))
    return m, None


def included_models(snapshot, overrides, probes):
    kept, dropped = [], []
    for raw in snapshot["models"]:
        m, reason = resolve(raw, overrides, probes)
        (dropped if reason else kept).append((m, reason))
    return [m for m, _ in kept], dropped


# ── probe ────────────────────────────────────────────────────────────────────

WEATHER_TOOL = [{"type": "function", "function": {
    "name": "get_weather", "description": "Get current weather for a city",
    "parameters": {"type": "object", "properties": {"city": {"type": "string"}}, "required": ["city"]},
}}]


def _post(path, body, key, anthropic=False):
    headers = {"x-api-key": key, "anthropic-version": "2023-06-01"} if anthropic else {"Authorization": f"Bearer {key}"}
    try:
        return 200, http_json(f"{API_BASE}{path}", body, headers, timeout=120)
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode(errors="replace")[:300]
    except Exception as exc:
        return 0, str(exc)[:300]


COLORS = {"red": (230, 30, 30), "green": (30, 170, 60), "blue": (30, 60, 220)}


def _color_png_uri(rgb, size=64):
    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    raw = b"".join(b"\x00" + bytes(rgb) * size for _ in range(size))
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))
    return "data:image/png;base64," + base64.b64encode(png).decode()


def _cos(a, b):
    return sum(x * y for x, y in zip(a, b)) / math.sqrt(sum(x * x for x in a) * sum(y * y for y in b))


def probe_image(m, key):
    """Does the model use image content, sent the way the plugin sends it at runtime?

    Accepting an image is not enough (some models silently embed the data URI as text, or
    return near-identical vectors for every image), so each solid-colour square must match
    its own caption: by cosine similarity for embeddings, as the top hit for rerank.
    """
    images = {c: _color_png_uri(rgb) for c, rgb in COLORS.items()}
    captions = [f"a solid {c} square" for c in COLORS]
    hits = 0
    if m["type"] == "text-embedding":
        vectors = []
        for item in [*images.values(), *captions]:
            status, body = _post("/api/v1/embeddings", {"model": m["id"], "input": [item]}, key)
            if status != 200:
                return f"error:{status}"
            vectors.append(body["data"][0]["embedding"])
        for i in range(len(COLORS)):
            sims = [_cos(vectors[i], vectors[len(COLORS) + j]) for j in range(len(COLORS))]
            hits += sims.index(max(sims)) == i
    else:
        for i, uri in enumerate(images.values()):
            status, body = _post("/api/v1/rerank", {"model": m["id"], "parameters": {"top_n": len(COLORS)},
                                                    "input": {"query": {"image": uri}, "documents": [{"text": c} for c in captions]}}, key)
            if status != 200:
                return f"error:{status}"
            results = body.get("results") or []
            hits += bool(results) and max(results, key=lambda r: r["relevance_score"])["index"] == i
    return "ok" if hits == len(COLORS) else f"mismatch {hits}/{len(COLORS)}"


def probe_model(m, key):
    mid, proto, result = m["id"], protocol_of(m["id"]), {"checked_at": today()}
    if m["type"] in ("text-embedding", "rerank"):
        if m["type"] == "text-embedding":
            status, body = _post("/api/v1/embeddings", {"model": mid, "input": ["alpha", "beta", "gamma"]}, key)
            result["batch_ok"] = status == 200 and len(body.get("data", [])) == 3
        if "image" in m["input"]:
            result["image"] = probe_image(m, key)
        return result
    if m["type"] != "llm":
        return result
    # The catalog keeps listing some retired models; a plain request tells us.
    status, body = _post("/api/v1/chat/completions", {
        "model": mid, "max_tokens": 16, "messages": [{"role": "user", "content": "hi"}]}, key)
    dead = status in (400, 404, 500) and re.search(r"deprecated|no longer available|does not exist|not found", str(body), re.I)
    result["alive"] = not dead
    if dead:
        result["error"] = re.sub(r"\s*\(request_id[^)]*\)", "", str(body))[:200]
        return result
    if proto == "openai":
        status, body = _post("/api/v1/chat/completions", {
            "model": mid, "max_tokens": 512, "tools": WEATHER_TOOL,
            "messages": [{"role": "user", "content": "What's the weather in Paris right now? Use the tool."}],
        }, key)
        if status == 200:
            calls = (body["choices"][0].get("message") or {}).get("tool_calls")
            result["tools"] = "called" if calls else "ignored"
        else:
            result["tools"] = f"rejected:{status}"
        if mid.startswith("openai/") and m.get("reasoning"):
            ok = []
            for effort in ALL_EFFORTS:
                status, body = _post("/api/v1/chat/completions", {
                    "model": mid, "max_tokens": 16, "reasoning_effort": effort,
                    "messages": [{"role": "user", "content": "hi"}],
                }, key)
                if status == 200 or (status == 400 and "max_output_tokens" in str(body)):
                    ok.append(effort)
            result["effort"] = ok
    elif proto == "anthropic":
        msgs = [{"role": "user", "content": "hi"}]
        status, _ = _post("/api/anthropic/v1/messages", {"model": mid, "max_tokens": 16, "temperature": 0.5, "messages": msgs}, key, anthropic=True)
        result["temperature"] = status == 200
        status, _ = _post("/api/anthropic/v1/messages", {"model": mid, "max_tokens": 1024, "thinking": {"type": "adaptive"}, "messages": msgs}, key, anthropic=True)
        result["adaptive"] = status == 200
    return result


def cmd_probe(args):
    key = os.environ.get("ZENMUX_PROBE_API_KEY")
    if not key:
        sys.exit("set ZENMUX_PROBE_API_KEY (a PAYG key is recommended; probes cost well under $1 in total)")
    snapshot, overrides, probes = load_inputs()
    models, _ = included_models(snapshot, overrides, {})  # re-probe retired models too
    if args.only:
        models = [m for m in models if any(re.search(p, m["id"]) for p in args.only)]
    elif not args.all:
        models = [m for m in models if m["id"] not in probes]
    print(f"probing {len(models)} models ...", file=sys.stderr)
    data = load_json(PROBES, {"models": {}})
    with concurrent.futures.ThreadPoolExecutor(args.workers) as pool:
        for m, res in zip(models, pool.map(lambda x: probe_model(x, key), models)):
            data["models"][m["id"]] = res
            print(f"  {m['id']:45} {json.dumps({k: v for k, v in res.items() if k != 'checked_at'})}", file=sys.stderr)
    data["models"] = dict(sorted(data["models"].items()))
    PROBES.write_text(json.dumps(data, indent=1) + "\n")


# ── parameter rule templates ─────────────────────────────────────────────────

def i18n(en, zh):
    return {"en_US": en, "zh_Hans": zh}


def use(name, template=None, **kw):
    return {"name": name, "use_template": template or name, **kw}


def max_tokens_rule(max_out, name="max_tokens"):
    return use(name, "max_tokens", required=True, default=min(max_out, DEFAULT_MAX_TOKENS), min=1, max=max_out)


def response_format(options):
    return {"name": "response_format", "label": i18n("Response Format", "回复格式"), "type": "string",
            "help": i18n("specifying the format that the model must output", "指定模型必须输出的格式"),
            "required": False, "options": options}


ENABLE_THINKING = {
    "name": "enable_thinking", "type": "boolean", "required": False, "default": False,
    "label": i18n("Thinking Mode", "推理模式"),
    "help": i18n("Whether to enable thinking mode. Models that always reason ignore this switch.",
                 "是否启用思考模式。始终推理的模型会忽略此开关。"),
}
HIDE_REASONING = {
    "name": "exclude_reasoning_tokens", "type": "boolean", "required": False, "default": False,
    "label": i18n("Hide the thought process", "隐藏思考过程"),
    "help": i18n("Drop the streamed thought process from the output.", "不在输出中展示思考过程。"),
}
JSON_SCHEMA = use("json_schema")


def generic_rules(m, max_out):
    known = set(m.get("params") or [])

    def supports(p):
        return not known or p in known

    rules = [use(p) for p in ("temperature", "top_p") if supports(p)]
    rules.append(max_tokens_rule(max_out))
    if supports("response_format"):
        rules.append(response_format(["text", "json_object"]))
    if m.get("reasoning"):
        rules += [ENABLE_THINKING, HIDE_REASONING]
    return rules


def openai_effort_options(model_id, probe):
    if probe.get("effort"):
        return probe["effort"]
    name = model_id.split("/", 1)[1]
    if re.match(r"o\d", name):
        return ["low", "medium", "high"]
    if re.match(r"gpt-(5\.[6-9]|[6-9])", name):
        return ["none", "low", "medium", "high", "xhigh", "max"]
    if re.match(r"gpt-5\.[2-5]", name):
        return ["none", "low", "medium", "high", "xhigh"]
    if name.startswith("gpt-5.1"):
        return ["none", "low", "medium", "high"]
    return ["minimal", "low", "medium", "high"]


def openai_rules(m, max_out, probe):
    known = set(m.get("params") or [])

    def supports(p):
        return not known or p in known

    rules = [use(p) for p in ("temperature", "top_p", "presence_penalty", "frequency_penalty") if supports(p)]
    rules += [max_tokens_rule(max_out), response_format(["text", "json_object", "json_schema"]), JSON_SCHEMA]
    if m.get("reasoning"):
        rules.append({"name": "reasoning_effort", "label": i18n("Reasoning Effort", "推理程度"), "type": "string",
                      "help": i18n("Constrains effort on reasoning.", "指定模型推理的程度"), "required": False,
                      "options": openai_effort_options(m["id"], probe)})
        if re.match(r"openai/gpt-([5-9])", m["id"]):
            rules.append({"name": "verbosity", "label": i18n("Verbosity", "回复详细度"), "type": "string",
                          "help": i18n("Controls the verbosity and length of the model response.", "控制模型响应的详细程度和长度。"),
                          "required": False, "options": ["low", "medium", "high"]})
    return rules


def anthropic_rules(m, max_out, probe):
    rules = []
    has_temperature = probe.get("temperature", True)
    if has_temperature:
        rules.append(use("temperature", default=1.0, min=0.0, max=1.0))
    rules.append(max_tokens_rule(max_out))
    if m.get("reasoning"):
        rules.append({**ENABLE_THINKING, "help": i18n(
            "Extended thinking. When enabled, temperature is ignored.", "扩展思考。启用后忽略 temperature。")
            if has_temperature else i18n("Adaptive extended thinking.", "自适应扩展思考。")})
        if not probe.get("adaptive"):
            rules.append({"name": "reasoning_budget", "type": "int", "required": False, "default": 2048,
                          "min": 1024, "max": max(1024, min(max_out - 1, 64000)),
                          "label": i18n("Thinking Budget", "推理预算"),
                          "help": i18n("Token budget for thinking; must be less than max_tokens.",
                                       "推理的 token 预算，必须小于 max_tokens。")})
        rules.append(HIDE_REASONING)
    rules += [response_format(["text", "json_schema"]), JSON_SCHEMA]
    return rules


GEMINI_TOOLS = [
    {"name": "grounding", "type": "boolean", "required": False, "default": False,
     "label": i18n("Grounding", "事实核查"), "help": i18n("Grounding with Google Search", "Google 事实核查")},
    {"name": "url_context", "type": "boolean", "required": False, "default": False,
     "label": i18n("URL context", "链接详情"), "help": i18n("Browse the url context", "获取并分析链接的详细信息，为回答提供参考依据。")},
    {"name": "code_execution", "type": "boolean", "required": False, "default": False,
     "label": i18n("Code execution", "代码执行"), "help": i18n("Lets Gemini use code to solve complex tasks", "让 Gemini 使用代码来解决复杂任务。")},
]
INCLUDE_THOUGHTS = {"name": "include_thoughts", "type": "boolean", "required": False, "default": False,
                    "label": i18n("Include thoughts", "返回思考过程"),
                    "help": i18n("Whether to include thoughts in the response.", "是否返回思考过程。")}


def gemini_rules(m, max_out):
    rules = [use("temperature", default=1.0, min=0.0, max=2.0), use("top_p")]
    rules.append(max_tokens_rule(max_out, name="max_output_tokens"))
    if m.get("reasoning"):
        rules.append(INCLUDE_THOUGHTS)
        if m["id"].startswith("google/gemini-2."):
            rules.append({"name": "thinking_mode", "type": "boolean", "required": False, "default": True,
                          "label": i18n("Thinking mode", "思考模式"),
                          "help": i18n("Turn thinking on/off. On without a budget means dynamic thinking.",
                                       "是否开启思考。开启且未设置预算时为动态预算。")})
            rules.append({"name": "thinking_budget", "type": "int", "required": False, "min": 1, "max": min(32768, max_out),
                          "label": i18n("Thinking budget", "思考预算"),
                          "help": i18n("Thinking token budget; only used when thinking mode is on.", "思考 token 预算，仅在思考模式开启时生效。")})
        else:
            rules.append({"name": "thinking_level", "type": "string", "required": False, "options": ["Low", "High"],
                          "label": i18n("Thinking level", "思考层级"),
                          "help": i18n("Thinking depth; model default when unset.", "思考深度，不设置时使用模型默认值。")})
    rules.append({"name": "media_resolution", "type": "string", "required": False,
                  "options": ["Default", "Low", "Medium", "High"], "label": i18n("Media resolution", "媒体分辨率"),
                  "help": i18n("Visual processing quality; higher costs more tokens.", "多模态视觉处理质量，越高越耗 token。")})
    return rules + GEMINI_TOOLS + [JSON_SCHEMA]


# ── build ────────────────────────────────────────────────────────────────────

def file_stem(model_id, taken):
    stem = model_id.split("/", 1)[1]
    if stem in taken:
        stem = model_id.replace("/", "-")
    taken.add(stem)
    return stem


def price_block(price, with_output=True):
    def fmt(v):
        return f"{float(v):.4f}".rstrip("0").rstrip(".") if v is not None else "0"

    block = {"input": fmt(price["input"])}
    if with_output:
        block["output"] = fmt(price.get("output"))
    return {**block, "unit": "0.000001", "currency": "USD"}


def llm_features(m, probe):
    proto = protocol_of(m["id"])
    # Probe "called" is conclusive; "rejected" means the endpoint errors on tool requests;
    # "ignored" (answered in text) or no probe falls back to the website parameter list.
    tools, known = probe.get("tools"), m.get("params") or []
    if tools == "called":
        has_tools = True
    elif tools and tools.startswith("rejected"):
        has_tools = False
    else:
        has_tools = proto != "openai" or not known or "tools" in known
    feats = ["tool-call", "multi-tool-call", "stream-tool-call"] if has_tools else []
    if m.get("reasoning"):
        feats.append("agent-thought")
    modal = {"image": "vision", "video": "video", "audio": "audio", "file": "document"}
    feats += [f for k, f in modal.items() if k in m["input"]]
    removed = set(m.get("features_remove") or [])
    return [f for f in feats + list(m.get("features_add") or []) if f not in removed]


def build_llm(m, probe):
    context = m.get("context") or 0
    max_out = m.get("max_output") or min(context or DEFAULT_MAX_TOKENS, DEFAULT_MAX_TOKENS)
    if context:
        max_out = min(max_out, context)
    proto = protocol_of(m["id"])
    if proto == "anthropic":
        rules = anthropic_rules(m, max_out, probe)
    elif proto == "google":
        rules = gemini_rules(m, max_out)
    elif m["id"].startswith("openai/"):
        rules = openai_rules(m, max_out, probe)
    else:
        rules = generic_rules(m, max_out)
    removed = set(m.get("params_remove") or [])
    rules = [r for r in rules if r["name"] not in removed]
    return {
        "model": m["id"], "label": i18n(m["name"], m["name"]), "model_type": "llm",
        "features": llm_features(m, probe),
        "model_properties": {"mode": "chat", "context_size": context},
        "parameter_rules": rules, "pricing": price_block(m["price"]),
    }


def retrieval_features(m, probe):
    """Dify (>= 1.11) treats embedding/rerank models listing `vision` as multimodal and sends images.

    The catalog's input modalities are not trusted on their own: `vision` needs a passing image probe.
    """
    feats = ["vision"] if "image" in m["input"] and probe.get("image") == "ok" else []
    removed = set(m.get("features_remove") or [])
    kept = [f for f in feats + list(m.get("features_add") or []) if f not in removed]
    return {"features": kept} if kept else {}


def build_embedding(m, probe):
    max_chunks = m.get("max_chunks") or (2048 if probe.get("batch_ok", True) else 1)
    return {
        "model": m["id"], "label": i18n(m["name"], m["name"]), "model_type": "text-embedding",
        **retrieval_features(m, probe),
        "model_properties": {"context_size": m.get("context") or 8192, "max_chunks": max_chunks},
        "pricing": price_block(m["price"], with_output=False),
    }


def build_rerank(m, probe):
    return {"model": m["id"], "label": i18n(m["name"], m["name"]), "model_type": "rerank",
            **retrieval_features(m, probe),
            "model_properties": {"context_size": m.get("context") or 8192}}


BUILDERS = {"llm": build_llm, "text-embedding": build_embedding, "rerank": build_rerank}


def build_all():
    snapshot, overrides, probes = load_inputs()
    models, dropped = included_models(snapshot, overrides, probes)
    order = {p: i for i, p in enumerate(overrides.get("provider_order") or [])}
    files = {}
    for mtype, folder in MODEL_DIRS.items():
        group = [m for m in models if m["type"] == mtype]
        group.sort(key=lambda m: (order.get(m["id"].split("/")[0], len(order)), "-" + (m.get("publish_time") or ""), m["id"]))
        taken = set()
        for m in sorted(group, key=lambda m: m["id"]):
            stem = file_stem(m["id"], taken)
            files[folder / f"{stem}.yaml"] = GENERATED_HEADER + dump_yaml(BUILDERS[mtype](m, probes.get(m["id"], {})))
        if group:
            files[folder / "_position.yaml"] = GENERATED_HEADER + dump_yaml([m["id"] for m in group])
    return files, models, dropped, snapshot


def existing_files():
    out = {}
    for folder in MODEL_DIRS.values():
        if folder.exists():
            out.update({p: p.read_text() for p in folder.glob("*.yaml")})
    return out


def summarize(old_text, new_text):
    old, new = yaml.safe_load(old_text) or {}, yaml.safe_load(new_text) or {}
    if isinstance(old, list) or isinstance(new, list):
        return ["order changed"]
    notes = []
    o_ctx, n_ctx = (old.get("model_properties") or {}).get("context_size"), (new.get("model_properties") or {}).get("context_size")
    if o_ctx != n_ctx:
        notes.append(f"context {o_ctx}→{n_ctx}")
    op, np_ = old.get("pricing") or {}, new.get("pricing") or {}
    for k in ("input", "output"):
        if k in np_ and (op.get(k) is None or float(op.get(k)) != float(np_[k])):
            notes.append(f"price.{k} {op.get(k)}→{np_[k]}")
    of, nf = set(old.get("features") or []), set(new.get("features") or [])
    if of != nf:
        notes.append("features " + " ".join([f"+{f}" for f in sorted(nf - of)] + [f"-{f}" for f in sorted(of - nf)]))
    orules = {r["name"] for r in old.get("parameter_rules") or []}
    nrules = {r["name"] for r in new.get("parameter_rules") or []}
    if orules != nrules:
        notes.append("params " + " ".join([f"+{r}" for r in sorted(nrules - orules)] + [f"-{r}" for r in sorted(orules - nrules)]))
    return notes or ["formatting/details"]


def model_id_of(text):
    data = yaml.safe_load(text)
    return data.get("model") if isinstance(data, dict) else None


def cmd_sync(args):
    files, models, dropped, snapshot = build_all()
    probes = load_json(PROBES, {}).get("models", {})
    old = existing_files()
    added, removed, changed = [], [], []
    for path, text in files.items():
        if path.name.startswith("_"):
            continue
        if path not in old:
            added.append(model_id_of(text) or path.name)
        elif old[path] != text:
            changed.append((model_id_of(text), summarize(old[path], text)))
    removed = [model_id_of(t) or p.name for p, t in old.items() if p not in files]
    if not args.dry_run:
        for path in old:
            if path not in files:
                path.unlink()
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    counts = {t: sum(1 for m in models if m["type"] == t) for t in MODEL_DIRS}
    lines = [f"## Model sync (catalog snapshot {snapshot.get('fetched_at')})", "",
             f"Included: {counts}. Excluded: {len(dropped)}.", ""]
    for title, items in (("Added", sorted(filter(None, added))), ("Removed", sorted(filter(None, removed)))):
        if items:
            lines += [f"### {title} ({len(items)})", ", ".join(f"`{i}`" for i in items), ""]
    if changed:
        lines += [f"### Changed ({len(changed)})"] + [f"- `{mid}`: {'; '.join(n)}" for mid, n in sorted(changed, key=lambda x: str(x[0]))] + [""]
    tiered = [m["id"] for m in models if m.get("tiered")]
    if tiered:
        lines += [f"### Tiered pricing ({len(tiered)}) - YAML holds the base tier; Dify records the per-request `usage.cost` where ZenMux returns it",
                  ", ".join(f"`{i}`" for i in tiered), ""]
    unverified = [(m["id"], (probes.get(m["id"]) or {}).get("image", "not probed")) for m in models
                  if m["type"] != "llm" and "image" in m["input"] and (probes.get(m["id"]) or {}).get("image") != "ok"]
    if unverified:
        lines += ["### Image input listed in the catalog but not verified - shipped text-only (re-probe to re-check)"]
        lines += [f"- `{mid}`: {res}" for mid, res in unverified] + [""]
    lines += ["### Excluded"] + [f"- `{m['id']}`: {r}" for m, r in sorted(dropped, key=lambda x: x[0]["id"])]
    print("\n".join(lines))


def cmd_check(_args):
    files, *_ = build_all()
    old = existing_files()
    drift = sorted({str(p.relative_to(ROOT)) for p in set(files) ^ set(old)} |
                   {str(p.relative_to(ROOT)) for p in files if p in old and old[p] != files[p]})
    if drift:
        print("YAMLs are out of sync with catalog/ (run `sync`):\n  " + "\n  ".join(drift))
        sys.exit(1)
    print(f"ok: {len(files)} generated files match catalog/")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("fetch")
    p = sub.add_parser("probe")
    p.add_argument("--only", nargs="*", help="regex filters on model id")
    p.add_argument("--all", action="store_true", help="re-probe models that already have results")
    p.add_argument("--workers", type=int, default=4)
    s = sub.add_parser("sync")
    s.add_argument("--dry-run", action="store_true")
    sub.add_parser("check")
    args = ap.parse_args()
    {"fetch": cmd_fetch, "probe": cmd_probe, "sync": cmd_sync, "check": cmd_check}[args.cmd](args)


if __name__ == "__main__":
    main()
